#!/usr/bin/env sh

## Description: Destroys and rebuilds the DDEV environment. This will delete and reinstall all dependencies.
## Usage: rebuild
## Example: "ddev rebuild"

# https://git.drupalcode.org/project/drupal_cms/-/blob/1.x/.ddev/commands/host/rebuild
ddev drush sql:drop -y
rm -r -f src/vendor src/composer.lock
ddev restart
