name: kingly-drupal
type: drupal10
docroot: src/web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
upload_dirs:
    - sites/default/files
use_dns_when_possible: true
composer_root: src
composer_version: "2"
web_environment:
    - COMPOSER_NO_AUDIT=1
corepack_enable: false
