hooks:
  post-start:
    - composer: install
    # Install
    - exec: drush site:install minimal -y
    # Recipes
    - exec: drush recipe ../recipes/contrib/kingly
    # Install npm dependencies
    - exec: cd src/web/modules/contrib/kingly_sdc && npm install
    # Development
    - exec: drush php:eval "\Drupal::keyValue('development_settings')->setMultiple(['disable_rendered_output_cache_bins' => TRUE, 'twig_debug' => TRUE, 'twig_cache_disable' => TRUE]);"
    - exec: drush en default_content -y
    - exec: drush en devel_generate -y
    - exec: drush pathauto:aliases-generate create canonical_entities:node
    # Finalize
    - exec: drush cron
    - exec: drush cache:rebuild
    # Launch
    - exec-host: ddev launch $(ddev drush uli)
